/**
 * The command registry (CONCEPT.md §7, M1-PLAN.md D3). Menus, keybindings,
 * the command bar and pane headers are all generated by filtering this
 * registry — nothing is wired up individually (D-026). Modules that define
 * commands register them as an import side effect; `main.tsx` (or a future
 * `commands/builtins.ts` barrel) is responsible for importing every such
 * module so its commands actually end up in the registry.
 */
import type { ContextExpression, ContextKeys } from './context'
import { compileContextExpression } from './context'
import type { Pane } from '../focus'
import type { DocumentSession } from '../session/documentSession'

// M5d-PLAN.md R2/R3 — `'titleBar'` is the drawn title bar's own surface
// (D-055: window + document scope), replacing the retired command bar —
// `'commandBar'` is gone from this union now that everything it held has
// somewhere to go (R2's pane toggles, R7's Save/Undo/Redo).
export type Surface = 'palette' | 'titleBar' | 'paneHeader' | 'contextMenu'

/** Resolved against the Fluent System Icons set by `commands/icons.ts`
 * (D8, CONCEPT.md §9.5) — a bare identifier, not a component reference or
 * asset path, so a command module doesn't need to know how icons are
 * sourced. */
export type IconRef = string

/**
 * What a command's `run()` receives. Grows as later tasks land — D6
 * (document session) is the first to add to it beyond the context-key
 * store; D9/D14 (navigation) will add more.
 */
export interface AppContext {
  readonly context: ContextKeys
  /** The active document session (D6) — `openFileDialog`, `cancel`, and
   * the rest of `DocumentSession`. Always the same instance in M1 (one
   * document, no tabs); a future tab strip would resolve this to whichever
   * tab is focused instead of a fixed singleton. */
  readonly session: DocumentSession
}

export interface Command {
  readonly id: string
  readonly title: string
  readonly category: string
  readonly icon?: IconRef
  readonly when?: ContextExpression
  /** M5d-PLAN.md R7 (D-055): a *separate* gate from `when`. `when` decides
   * whether a command exists on a surface at all — that's what the palette
   * and pane headers still use, unchanged, so a currently-pointless action
   * (M3-PLAN.md F9's `canUndo`/`canRedo`) stays hidden there exactly as
   * before. The title bar needs the opposite: "disabled, not hidden" is
   * D-055's own constraint, because a button that disappears when unusable
   * reflows the strip and destroys pointer muscle memory — so it renders
   * every `titleBar` command regardless of `when` (`commandsForSurfaceUnfiltered`
   * below) and greys it out using `enabledWhen` instead. Commands with no
   * `enabledWhen` are always enabled wherever they're rendered. */
  readonly enabledWhen?: ContextExpression
  readonly surfaces: readonly Surface[]
  readonly weight?: number
  /** Which pane's header this belongs to — only meaningful alongside
   * `surfaces: ['paneHeader']`. Pane headers are per-pane chrome (§4.1's
   * "thin, flat header strips per pane"), so a `paneHeader` command needs
   * to say which one it renders in; `when` alone can't express that, since
   * it gates on live context (e.g. which pane has focus), not "which
   * pane's header is this button drawn into" — a Tree command belongs in
   * Tree's header whether or not Tree currently has focus. */
  readonly pane?: Pane
  /** R68 (`R66-palette-polish.md` §3): present exactly for a toggle
   * command, and `state !== undefined` **is** the definition of "this
   * command is a toggle" — nothing else checks the id or the title to
   * decide. The palette renders it as a trailing On/Off (R66/R68);
   * `tooltipFor` (`uiHelpers.ts`) prefixes `Toggle ` on an icon-only button
   * exactly because it's set, rather than the title storing the verb
   * itself — the same "the title stores the name, the surface composes the
   * rest" move D-055 already made for the chord. Called fresh on every
   * render, never cached — deliberately a synchronous getter, not a value,
   * so it's always this instant's real state. */
  readonly state?: () => boolean
  run(ctx: AppContext): void
}

const commands = new Map<string, Command>()

/**
 * Throws on a duplicate id in dev builds only (`import.meta.env.DEV`,
 * CLAUDE.md's convention for dev-only assertions) — a silent overwrite in
 * production is preferable to a crash over a naming collision a user can't
 * fix. The "every surfaced command is palette-reachable" invariant is
 * deliberately *not* enforced here — CONCEPT.md §7 and M1-PLAN.md D3 both
 * specify it as a test over the live registry (`test/commands.test.ts`),
 * not a registration-time throw, so it still catches a later task's
 * mistake without adding friction for a test that registers a narrow,
 * intentionally-restricted command for its own purposes.
 */
export function registerCommand(command: Command): void {
  if (import.meta.env?.DEV && commands.has(command.id)) {
    throw new Error(`Duplicate command id: ${command.id}`)
  }
  // Compile `when` now, and unconditionally — not dev-only like the
  // duplicate-id check above. A malformed expression is a typo in a source
  // literal, and the alternative is not "no throw" but "throws later, from
  // inside whichever surface queried first", where one bad command takes
  // down the palette, the command bar and every pane header at once.
  // Failing at registration is strictly the better crash, and it warms the
  // parse cache so `commandsForSurface` never re-parses.
  if (command.when !== undefined) compileContextExpression(command.when)
  if (command.enabledWhen !== undefined) compileContextExpression(command.enabledWhen)
  commands.set(command.id, command)
}

export function getCommand(id: string): Command | undefined {
  return commands.get(id)
}

export function getAllCommands(): readonly Command[] {
  return [...commands.values()]
}

/** Commands visible on `surface`, filtered by `when` against `context` and
 * ordered by `weight` (ties keep registration order — `Array#sort` is
 * stable). Missing `when` means always visible. */
export function commandsForSurface(surface: Surface, context: ContextKeys): Command[] {
  return getAllCommands()
    .filter((command) => command.surfaces.includes(surface))
    .filter(
      (command) => command.when === undefined || compileContextExpression(command.when)(context)
    )
    .sort((a, b) => (a.weight ?? 0) - (b.weight ?? 0))
}

/** M5d-PLAN.md R7 — the title bar's own lookup, deliberately not
 * `when`-filtered (see `Command.enabledWhen`'s own doc comment for why).
 * Ordered by `weight` the same way `commandsForSurface` is. */
export function commandsForSurfaceUnfiltered(surface: Surface): Command[] {
  return getAllCommands()
    .filter((command) => command.surfaces.includes(surface))
    .sort((a, b) => (a.weight ?? 0) - (b.weight ?? 0))
}

/** `true` when `command` has no `enabledWhen` (always enabled) or its
 * `enabledWhen` evaluates truthy against `context`. */
export function isCommandEnabled(command: Command, context: ContextKeys): boolean {
  return command.enabledWhen === undefined || compileContextExpression(command.enabledWhen)(context)
}

/** Test-only: clears the registry between test cases — it's a module-level
 * singleton so real command modules can register via import side effects. */
export function resetCommandRegistryForTests(): void {
  commands.clear()
}
